mod day1;
mod day2;
mod day3;
mod day4;
mod day5;
mod day6;
mod day7;
mod day8;

fn main() {
  println!("DAY1 ---");
  day1::first_task();
  day1::second_task();
  println!("");
  println!("DAY2 ---");
  day2::first_task();
  day2::second_task();
  println!("");
  println!("DAY3 ---");
  day3::first_task();
  day3::second_task();
  println!("");
  println!("DAY4 ---");
  day4::first_task();
  day4::second_task();
  println!("");
  println!("DAY5 ---");
  day5::first_task();
  day5::second_task();
  println!("");
  println!("DAY6 ---");
  day6::first_task();
  day6::second_task();
  println!("");
  println!("DAY7 ---");
  day7::first_task();
  day7::second_task();
  println!("");
  println!("DAY8 ---");
  day8::first_task();
  day8::second_task();
}
